In [8]:
df = pd.read_excel(archivo_dgt)

In [9]:
df.shape

(101996, 73)

In [10]:
df.head()

,ID_ACCIDENTE,ANYO,MES,DIA_SEMANA,HORA,COD_PROVINCIA,COD_MUNICIPIO,ISLA,ZONA,ZONA_AGRUPADA,...,PRIORI_OTRA,CONDICION_NIVEL_CIRCULA,CONDICION_FIRME,CONDICION_ILUMINACION,CONDICION_METEO,CONDICION_NIEBLA,CONDICION_VIENTO,VISIB_RESTRINGIDA_POR,ACERA,TRAZADO_PLANTA
0,1,2024,1,3,22,1,0,NaN,1,1,...,999,1,1,6,1,NaN,NaN,1,998,1
1,2,2024,1,6,23,1,1036,NaN,1,1,...,999,1,3,6,4,NaN,NaN,1,998,3
2,3,2024,1,7,1,1,0,NaN,1,1,...,999,1,3,6,3,NaN,NaN,1,998,1
3,4,2024,1,7,8,1,0,NaN,1,1,...,999,1,3,1,3,NaN,NaN,1,998,3
4,5,2024,1,4,17,1,0,NaN,1,1,...,999,1,3,1,2,NaN,NaN,1,998,1

In [11]:
df.columns.tolist()

['ID_ACCIDENTE',
 'ANYO',
 'MES',
 'DIA_SEMANA',
 'HORA',
 'COD_PROVINCIA',
 'COD_MUNICIPIO',
 'ISLA',
 'ZONA',
 'ZONA_AGRUPADA',
 'CARRETERA',
 'KM',
 'SENTIDO_1F',
 'TITULARIDAD_VIA',
 'TIPO_VIA',
 'TIPO_ACCIDENTE',
 'TOTAL_MU24H',
 'TOTAL_HG24H',
 'TOTAL_HL24H',
 'TOTAL_VICTIMAS_24H',
 'TOTAL_MU30DF',
 'TOTAL_HG30DF',
 'TOTAL_HL30DF',
 'TOTAL_VICTIMAS_30DF',
 'TOTAL_VEHICULOS',
 'TOT_PEAT_MU24H',
 'TOT_BICI_MU24H',
 'TOT_CICLO_MU24H',
 'TOT_MOTO_MU24H',
 'TOT_TUR_MU24H',
 'TOT_FURG_MU24H',
 'TOT_CAM_MENOS3500_MU24H',
 'TOT_CAM_MAS3500_MU24H',
 'TOT_BUS_MU24H',
 'TOT_OTRO_MU24H',
 'TOT_SINESPECIF_MU24H',
 'TOT_PEAT_MU30DF',
 'TOT_BICI_MU30DF',
 'TOT_CICLO_MU30DF',
 'TOT_MOTO_MU30DF',
 'TOT_TUR_MU30DF',
 'TOT_FURG_MU30DF',
 'TOT_CAM_MENOS3500_MU30DF',
 'TOT_CAM_MAS3500_MU30DF',
 'TOT_BUS_MU30DF',
 'TOT_VMP_MU30DF',
 'TOT_OTRO_MU30DF',
 'TOT_SINESPECIF_MU30DF',
 'NUDO',
 'NUDO_INFO',
 'CARRETERA_CRUCE',
 'PRIORI_NORMA',
 'PRIORI_AGENTE',
 'PRIORI_SEMAFORO',
 'PRIORI_VERT_STOP',
 'PRIORI_VERT_CEDA',
 'PRIORI_HORIZ_STOP',
 'PRIORI_HORIZ_CEDA',
 'PRIORI_MARCAS',
 'PRIORI_PEA_NO_ELEV',
 'PRIORI_PEA_ELEV',
 'PRIORI_MARCA_CICLOS',
 'PRIORI_CIRCUNSTANCIAL',
 'PRIORI_OTRA',
 'CONDICION_NIVEL_CIRCULA',
 'CONDICION_FIRME',
 'CONDICION_ILUMINACION',
 'CONDICION_METEO',
 'CONDICION_NIEBLA',
 'CONDICION_VIENTO',
 'VISIB_RESTRINGIDA_POR',
 'ACERA',
 'TRAZADO_PLANTA']

In [12]:
df["ID_ACCIDENTE"].nunique()

101996

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.isna().sum().sort_values(ascending=False)

CONDICION_VIENTO         101685
CARRETERA_CRUCE           99318
ISLA                      97552
CONDICION_NIEBLA          94514
KM                        63182
                          ...
CONDICION_FIRME               0
CONDICION_METEO               0
VISIB_RESTRINGIDA_POR         0
ACERA                         0
TRAZADO_PLANTA                0
Length: 73, dtype: int64

In [15]:
(df.isna().mean() * 100).sort_values(ascending=False)

CONDICION_VIENTO         99.695086
CARRETERA_CRUCE          97.374407
ISLA                     95.642966
CONDICION_NIEBLA         92.664418
KM                       61.945566
                           ...
CONDICION_FIRME           0.000000
CONDICION_METEO           0.000000
VISIB_RESTRINGIDA_POR     0.000000
ACERA                     0.000000
TRAZADO_PLANTA            0.000000
Length: 73, dtype: float64

In [16]:
df.dtypes

ID_ACCIDENTE               int64
ANYO                       int64
MES                        int64
DIA_SEMANA                 int64
HORA                       int64
                          ...
CONDICION_NIEBLA         float64
CONDICION_VIENTO         float64
VISIB_RESTRINGIDA_POR      int64
ACERA                      int64
TRAZADO_PLANTA             int64
Length: 73, dtype: object

In [17]:
df["MES"].value_counts().sort_index()

MES
1     7793
2     7837
3     8061
4     8610
5     8972
6     9052
7     9333
8     8026
9     8550
10    9231
11    8215
12    8316
Name: count, dtype: int64

In [18]:
df["COD_PROVINCIA"].value_counts()

COD_PROVINCIA
8     17945
28    14183
46     5779
29     5185
41     4748
30     3922
3      3758
7      2888
11     2707
43     2381
17     2247
33     1945
38     1937
35     1920
48     1849
36     1737
15     1713
50     1599
25     1542
4      1503
20     1438
18     1319
39     1203
6      1075
12     1066
23      959
45      918
47      889
1       867
2       854
31      842
14      812
21      743
26      669
37      660
9       655
13      546
10      517
22      437
52      413
19      410
24      403
32      397
27      391
5       363
40      345
51      300
16      268
44      254
49      227
34      151
42      117
Name: count, dtype: int64

In [19]:
archivo_diccionario = "../data/raw/dgt/Diccionario_Tabla_Accidentes.xlsx"

In [20]:
diccionario = pd.read_excel(archivo_diccionario)

In [21]:
diccionario.head()

  Unnamed: 0 Unnamed: 1
0      Valor   Etiqueta
1          1      LUNES
2          2     MARTES
3          3  MIÉRCOLES
4          4     JUEVES

In [22]:
pd.ExcelFile(archivo_diccionario).sheet_names

['DIA_SEMANA',
 'COD_PROVINCIA',
 'COD_MUNICIPIO',
 'ISLA',
 'ZONA',
 'ZONA_AGRUPADA',
 'CARRETERA',
 'KM',
 'SENTIDO_1F',
 'TITULARIDAD_VIA',
 'TIPO_VIA',
 'TIPO_ACCIDENTE',
 'TOTALIZADORES',
 'NUDO',
 'NUDO_INFO',
 'CARRETERA_CRUCE',
 'PRIORI_NORMA',
 'PRIORI_AGENTE',
 'PRIORI_SEMAFORO',
 'PRIORI_VERT_STOP',
 'PRIORI_VERT_CEDA',
 'PRIORI_HORIZ_STOP',
 'PRIORI_HORIZ_CEDA',
 'PRIORI_MARCAS',
 'PRIORI_PEA_NO_ELEV',
 'PRIORI_PEA_ELEV',
 'PRIORI_MARCA_CICLOS',
 'PRIORI_CIRCUNSTANCIAL',
 'PRIORI_OTRA',
 'CONDICION_NIVEL_CIRCULA',
 'CONDICION_FIRME',
 'CONDICION_ILUMINACION',
 'CONDICION_METEO',
 'CONDICION_NIEBLA',
 'CONDICION_VIENTO',
 'VISIB_RESTRINGIDA_POR',
 'ACERA',
 'TRAZADO_PLANTA']

In [23]:
provincias = pd.read_excel(
    archivo_diccionario,
    sheet_name="COD_PROVINCIA"
)

In [24]:
provincias.head(10)

  Unnamed: 0        Unnamed: 1
0      Valor          Etiqueta
1          1       Araba/Álava
2          2          Albacete
3          3  Alicante/Alacant
4          4           Almería
5          5             Ávila
6          6           Badajoz
7          7    Balears, Illes
8          8         Barcelona
9          9            Burgos

In [25]:
provincias = pd.read_excel(
    archivo_diccionario,
    sheet_name="COD_PROVINCIA",
    header=1
)

In [26]:
provincias.head()

   Valor          Etiqueta
0      1       Araba/Álava
1      2          Albacete
2      3  Alicante/Alacant
3      4           Almería
4      5             Ávila

In [27]:
provincias.columns.tolist()

['Valor', 'Etiqueta']

In [28]:
mapa_provincias = dict(zip(provincias["Valor"], provincias["Etiqueta"]))

In [29]:
mapa_provincias[46]

'Valencia/València'

In [30]:
df["PROVINCIA"] = df["COD_PROVINCIA"].map(mapa_provincias)

In [31]:
df[["COD_PROVINCIA", "PROVINCIA"]].head(10)

   COD_PROVINCIA    PROVINCIA
0              1  Araba/Álava
1              1  Araba/Álava
2              1  Araba/Álava
3              1  Araba/Álava
4              1  Araba/Álava
5              1  Araba/Álava
6              1  Araba/Álava
7              1  Araba/Álava
8              1  Araba/Álava
9              1  Araba/Álava

In [32]:
df["PROVINCIA"].value_counts().head(10)

PROVINCIA
Barcelona            17945
Madrid               14183
Valencia/València     5779
Málaga                5185
Sevilla               4748
Murcia                3922
Alicante/Alacant      3758
Balears, Illes        2888
Cádiz                 2707
Tarragona             2381
Name: count, dtype: int64

In [33]:
df["PROVINCIA"].value_counts().cumsum().head(10)

PROVINCIA
Barcelona            17945
Madrid               32128
Valencia/València    37907
Málaga               43092
Sevilla              47840
Murcia               51762
Alicante/Alacant     55520
Balears, Illes       58408
Cádiz                61115
Tarragona            63496
Name: count, dtype: int64

In [34]:
provincias_seleccionadas = [
    "Barcelona",
    "Madrid",
    "Valencia/València",
    "Málaga",
    "Sevilla",
    "Murcia"
]

In [35]:
df_seleccion = df[df["PROVINCIA"].isin(provincias_seleccionadas)].copy()

In [36]:
df_seleccion.shape

(51762, 74)

In [44]:
archivo_ine = "../data/raw/ine/Poblacion_24.csv"

In [46]:
df_ine = pd.read_csv(archivo_ine, sep=";", encoding="latin1")

In [47]:
df_ine.head()

,Total Nacional,Comunidades y Ciudades Autónomas,Provincias,Sexo,Periodo,Total
0,Total Nacional,NaN,NaN,Total,2024,48.619.695
1,Total Nacional,01 Andalucía,NaN,Total,2024,8.631.862
2,Total Nacional,01 Andalucía,04 Almería,Total,2024,760.964
3,Total Nacional,01 Andalucía,11 Cádiz,Total,2024,1.258.730
4,Total Nacional,01 Andalucía,14 Córdoba,Total,2024,774.313

In [48]:
df_ine.columns.tolist()

['Total Nacional',
 'Comunidades y Ciudades Autónomas',
 'Provincias',
 'Sexo',
 'Periodo',
 'Total']

In [49]:
df_ine_provincias = df_ine[df_ine["Provincias"].notna()].copy()

In [50]:
df_ine_provincias.shape

(52, 6)

In [51]:
df_ine_provincias["Provincias"].tolist()

['04 Almería',
 '11 Cádiz',
 '14 Córdoba',
 '18 Granada',
 '21 Huelva',
 '23 Jaén',
 '29 Málaga',
 '41 Sevilla',
 '22 Huesca',
 '44 Teruel',
 '50 Zaragoza',
 '33 Asturias',
 '07 Balears, Illes',
 '35 Palmas, Las',
 '38 Santa Cruz de Tenerife',
 '39 Cantabria',
 '05 Ávila',
 '09 Burgos',
 '24 León',
 '34 Palencia',
 '37 Salamanca',
 '40 Segovia',
 '42 Soria',
 '47 Valladolid',
 '49 Zamora',
 '02 Albacete',
 '13 Ciudad Real',
 '16 Cuenca',
 '19 Guadalajara',
 '45 Toledo',
 '08 Barcelona',
 '17 Girona',
 '25 Lleida',
 '43 Tarragona',
 '03 Alicante/Alacant',
 '12 Castellón/Castelló',
 '46 Valencia/València',
 '06 Badajoz',
 '10 Cáceres',
 '15 Coruña, A',
 '27 Lugo',
 '32 Ourense',
 '36 Pontevedra',
 '28 Madrid',
 '30 Murcia',
 '31 Navarra',
 '01 Araba/Álava',
 '48 Bizkaia',
 '20 Gipuzkoa',
 '26 Rioja, La',
 '51 Ceuta',
 '52 Melilla']

In [52]:
df_ine_provincias["COD_PROVINCIA"] = (
    df_ine_provincias["Provincias"]
    .str[:2]
    .astype(int)
)

In [53]:
df_ine_provincias[["Provincias", "COD_PROVINCIA"]].head(10)

    Provincias  COD_PROVINCIA
2   04 Almería              4
3     11 Cádiz             11
4   14 Córdoba             14
5   18 Granada             18
6    21 Huelva             21
7      23 Jaén             23
8    29 Málaga             29
9   41 Sevilla             41
11   22 Huesca             22
12   44 Teruel             44

In [54]:
df_ine_provincias["POBLACION_2024"] = (
    df_ine_provincias["Total"]
    .str.replace(".", "", regex=False)
    .astype(int)
)

In [55]:
df_ine_provincias[["Provincias", "Total", "POBLACION_2024"]].head(10)

    Provincias      Total  POBLACION_2024
2   04 Almería    760.964          760964
3     11 Cádiz  1.258.730         1258730
4   14 Córdoba    774.313          774313
5   18 Granada    939.741          939741
6    21 Huelva    535.734          535734
7      23 Jaén    619.055          619055
8    29 Málaga  1.774.701         1774701
9   41 Sevilla  1.968.624         1968624
11   22 Huesca    228.519          228519
12   44 Teruel    135.309          135309

In [56]:
df_ine_final = df_ine_provincias[
    ["COD_PROVINCIA", "Provincias", "POBLACION_2024"]
].copy()

In [57]:
df_ine_final.head()

   COD_PROVINCIA  Provincias  POBLACION_2024
2              4  04 Almería          760964
3             11    11 Cádiz         1258730
4             14  14 Córdoba          774313
5             18  18 Granada          939741
6             21   21 Huelva          535734

In [58]:
df_ine_final["COD_PROVINCIA"].duplicated().sum()

np.int64(0)

In [59]:
df_ine_final[
    df_ine_final["COD_PROVINCIA"].isin(
        df_seleccion["COD_PROVINCIA"].unique()
    )
]

    COD_PROVINCIA            Provincias  POBLACION_2024
8              29             29 Málaga         1774701
9              41            41 Sevilla         1968624
40              8          08 Barcelona         5877672
47             46  46 Valencia/València         2710808
57             28             28 Madrid         7009268
59             30             30 Murcia         1568492

In [60]:
df_final = df_seleccion.merge(
    df_ine_final[["COD_PROVINCIA", "POBLACION_2024"]],
    on="COD_PROVINCIA",
    how="left",
    validate="many_to_one"
)

In [61]:
df_final.shape

(51762, 75)

In [62]:
df_final["POBLACION_2024"].isna().sum()

np.int64(0)

In [66]:
Path("../data/processed/accidentes_2024_final.csv").exists()

True