In [1]:
import pandas as pd
from pathlib import Path

In [2]:
df = pd.read_csv("../data/processed/accidentes_2024_final.csv")

In [3]:
df.shape

(51762, 75)

In [4]:
df.isna().sum().sort_values(ascending=False).head(15)

ISLA                51700
CONDICION_VIENTO    51684
CARRETERA_CRUCE     50977
CONDICION_NIEBLA    44848
KM                  38676
NUDO_INFO           19901
TIPO_ACCIDENTE          7
NUDO                    5
MES                     0
ANYO                    0
ID_ACCIDENTE            0
CARRETERA               0
ZONA_AGRUPADA           0
ZONA                    0
COD_MUNICIPIO           0
dtype: int64

In [5]:
(df.isna().mean() * 100).sort_values(ascending=False).head(15)

ISLA                99.880221
CONDICION_VIENTO    99.849310
CARRETERA_CRUCE     98.483443
CONDICION_NIEBLA    86.642711
KM                  74.718906
NUDO_INFO           38.447123
TIPO_ACCIDENTE       0.013523
NUDO                 0.009660
MES                  0.000000
ANYO                 0.000000
ID_ACCIDENTE         0.000000
CARRETERA            0.000000
ZONA_AGRUPADA        0.000000
ZONA                 0.000000
COD_MUNICIPIO        0.000000
dtype: float64

In [6]:
df["ISLA"].value_counts(dropna=False)

ISLA
NaN    51700
0.0       62
Name: count, dtype: int64

In [7]:
isla_dic = pd.read_excel(
    "../data/raw/dgt/Diccionario_Tabla_Accidentes.xlsx",
    sheet_name="ISLA",
    header=1
)

isla_dic

    Valor       Etiqueta
0     NaN      No aplica
1     1.0       Mallorca
2     2.0        Menorca
3     3.0          Ibiza
4     4.0     Formentera
5     5.0        Cabrera
6     6.0       Conejera
7     7.0   Gran Canaria
8     8.0  Fuerteventura
9     9.0      Lanzarote
10   10.0       Tenerife
11   11.0       La Palma
12   12.0         Gomera
13   13.0         Hierro

In [8]:
df.loc[df["ISLA"] == 0, ["PROVINCIA", "ISLA"]]["PROVINCIA"].value_counts()

PROVINCIA
Valencia/València    32
Murcia               17
Madrid                6
Málaga                5
Sevilla               2
Name: count, dtype: int64

In [9]:
df = df.drop(columns=["ISLA"])

In [10]:
df["CONDICION_VIENTO"].value_counts(dropna=False)

CONDICION_VIENTO
NaN    51684
1.0       78
Name: count, dtype: int64

In [11]:
viento_dic = pd.read_excel(
    "../data/raw/dgt/Diccionario_Tabla_Accidentes.xlsx",
    sheet_name="CONDICION_VIENTO",
    header=1
)

viento_dic

  Valor                     Etiqueta
0     .  No se aprecia viento fuerte
1     1                Viento fuerte

In [12]:
viento_raw = pd.read_excel(
    "../data/raw/dgt/TABLA_ACCIDENTES_24.xlsx",
    usecols=["CONDICION_VIENTO"],
    keep_default_na=False
)

viento_raw["CONDICION_VIENTO"].value_counts(dropna=False)

CONDICION_VIENTO
     101685
1       311
Name: count, dtype: int64

In [13]:
df["CONDICION_VIENTO_DESC"] = df["CONDICION_VIENTO"].map({
    1: "Viento fuerte"
}).fillna("No se aprecia viento fuerte")

In [14]:
df["CONDICION_VIENTO_DESC"].value_counts()

CONDICION_VIENTO_DESC
No se aprecia viento fuerte    51684
Viento fuerte                     78
Name: count, dtype: int64

In [15]:
df["CONDICION_NIEBLA"].value_counts(dropna=False)

CONDICION_NIEBLA
NaN    44848
1.0     6897
2.0       17
Name: count, dtype: int64

In [16]:
niebla_dic = pd.read_excel(
    "../data/raw/dgt/Diccionario_Tabla_Accidentes.xlsx",
    sheet_name="CONDICION_NIEBLA",
    header=1
)

niebla_dic

   Valor        Etiqueta
0      1   Niebla ligera
1      2  Niebla intensa

In [17]:
niebla_raw = pd.read_excel(
    "../data/raw/dgt/TABLA_ACCIDENTES_24.xlsx",
    usecols=["CONDICION_NIEBLA"],
    keep_default_na=False
)

niebla_raw["CONDICION_NIEBLA"].value_counts(dropna=False)

CONDICION_NIEBLA
     94514
1     7351
2      131
Name: count, dtype: int64

In [18]:
pd.crosstab(
    df["CONDICION_METEO"],
    df["CONDICION_NIEBLA"],
    dropna=False
)

CONDICION_NIEBLA   1.0  2.0    NaN
CONDICION_METEO
1                 6493    3  39578
2                   40    6   1966
3                  308    5   2305
4                   52    0    509
5                    0    0      7
6                    0    0      4
7                    4    3    468
999                  0    0     11

In [19]:
meteo_dic = pd.read_excel(
    "../data/raw/dgt/Diccionario_Tabla_Accidentes.xlsx",
    sheet_name="CONDICION_METEO",
    header=1
)

meteo_dic

   Valor         Etiqueta
0      1        Despejado
1      2          Nublado
2      3     Lluvia débil
3      4    Lluvia fuerte
4      5       Granizando
5      6          Nevando
6      7     Se desconoce
7    999  Sin especificar

In [21]:
mapa_meteo = dict(zip(meteo_dic["Valor"], meteo_dic["Etiqueta"]))

df["CONDICION_METEO_DESC"] = df["CONDICION_METEO"].map(mapa_meteo)

In [22]:
df["CONDICION_METEO_DESC"].value_counts(dropna=False)

CONDICION_METEO_DESC
Despejado          46074
Lluvia débil        2618
Nublado             2012
Lluvia fuerte        561
Se desconoce         475
Sin especificar       11
Granizando             7
Nevando                4
Name: count, dtype: int64

In [23]:
df["CONDICION_NIEBLA_DESC"] = df["CONDICION_NIEBLA"].map({
    1: "Niebla ligera",
    2: "Niebla intensa"
}).fillna("Sin información")

In [24]:
df["CONDICION_NIEBLA_DESC"].value_counts()

CONDICION_NIEBLA_DESC
Sin información    44848
Niebla ligera       6897
Niebla intensa        17
Name: count, dtype: int64

In [25]:
df["CARRETERA_CRUCE"].value_counts(dropna=False)

CARRETERA_CRUCE
NaN       50977
A-7          31
M-50         26
M-40         16
A-4          15
          ...
2024          1
CV-411        1
CV-405        1
CV-473        1
CV-500        1
Name: count, Length: 336, dtype: int64

In [26]:
cruce_dic = pd.read_excel(
    "../data/raw/dgt/Diccionario_Tabla_Accidentes.xlsx",
    sheet_name="CARRETERA_CRUCE",
    header=1
)

cruce_dic.head(20)

   Valor          Etiqueta
0    NaN  Nombre carretera

In [27]:
df = df.drop(columns=["CARRETERA_CRUCE"])

In [28]:
df["KM"].value_counts(dropna=False).head(20)

KM
NaN     38676
1.0       152
0.5       144
0.0       137
0.1       115
2.0        99
1.5        90
2.5        88
10.0       85
3.5        83
7.0        79
3.0        79
4.5        70
5.0        69
9.0        68
0.9        68
9.5        67
8.0        66
11.0       64
8.5        63
Name: count, dtype: int64

In [29]:
km_dic = pd.read_excel(
    "../data/raw/dgt/Diccionario_Tabla_Accidentes.xlsx",
    sheet_name="KM",
    header=1
)

km_dic.head(20)

  Unnamed: 0  Unnamed: 1
0    Formato         7.2

In [30]:
pd.crosstab(
    df["ZONA"],
    df["KM"].isna()
)

KM    False  True
ZONA
1     12391     21
2       652     57
3        20  38598
4        23      0

In [31]:
zona_dic = pd.read_excel(
    "../data/raw/dgt/Diccionario_Tabla_Accidentes.xlsx",
    sheet_name="ZONA",
    header=1
)

zona_dic

   Valor                    Etiqueta
0      1                   Carretera
1      2                    Travesía
2      3                       Calle
3      4  Autopista o autovía urbana

In [32]:
mapa_zona = dict(zip(zona_dic["Valor"], zona_dic["Etiqueta"]))

df["ZONA_DESC"] = df["ZONA"].map(mapa_zona)

In [33]:
df["ZONA_DESC"].value_counts(dropna=False)

ZONA_DESC
Calle                         38618
Carretera                     12412
Travesía                        709
Autopista o autovía urbana       23
Name: count, dtype: int64

In [34]:
df["NUDO_INFO"].value_counts(dropna=False).head(20)

NUDO_INFO
NaN      19901
999.0    10972
1.0       8855
2.0       6095
4.0       4556
5.0        723
12.0       236
3.0        183
10.0       127
7.0         39
11.0        39
6.0         27
9.0          8
8.0          1
Name: count, dtype: int64

In [35]:
nudo_info_dic = pd.read_excel(
    "../data/raw/dgt/Diccionario_Tabla_Accidentes.xlsx",
    sheet_name="NUDO_INFO",
    header=1
)

nudo_info_dic

    Valor                                           Etiqueta
0       1                                           En X o +
1       2                                           En T o Y
2       3                                        En estrella
3       4                                           Glorieta
4       5                                   Glorieta partida
5       6                                       Miniglorieta
6       7                                     Glorieta doble
7       8                           Paso a nivel con barrera
8       9                           Paso a nivel sin barrera
9      10  Enlace con carriles de cambio de velocidad par...
10     11  Enlace sin carriles de cambio de velocidad par...
11     12                         Bifurcación o convergencia
12    999                                    Sin especificar

In [36]:
mapa_nudo_info = dict(zip(
    nudo_info_dic["Valor"],
    nudo_info_dic["Etiqueta"]
))

df["NUDO_INFO_DESC"] = df["NUDO_INFO"].map(mapa_nudo_info)

In [37]:
df["NUDO_INFO_DESC"].value_counts(dropna=False)

NUDO_INFO_DESC
NaN                                                               19901
Sin especificar                                                   10972
En X o +                                                           8855
En T o Y                                                           6095
Glorieta                                                           4556
Glorieta partida                                                    723
Bifurcación o convergencia                                          236
En estrella                                                         183
Enlace con carriles de cambio de velocidad paralelos al tronco      127
Glorieta doble                                                       39
Enlace sin carriles de cambio de velocidad paralelos al tronco       39
Miniglorieta                                                         27
Paso a nivel sin barrera                                              8
Paso a nivel con barrera                                              1
Name: count, dtype: int64

In [38]:
df["NUDO"].value_counts(dropna=False)

NUDO
2.0    26454
1.0    25303
NaN        5
Name: count, dtype: int64

In [39]:
nudo_dic = pd.read_excel(
    "../data/raw/dgt/Diccionario_Tabla_Accidentes.xlsx",
    sheet_name="NUDO",
    header=1
)

nudo_dic

   Valor                      Etiqueta
0      1        En intersección o nudo
1      2  Fuera de intersección o nudo

In [40]:
pd.crosstab(
    df["NUDO"],
    df["NUDO_INFO"].isna()
)

NUDO_INFO  False  True
NUDO
1.0        25303      0
2.0         6558  19896

In [41]:
df.loc[df["NUDO"] == 2, "NUDO_INFO"].value_counts(dropna=False)

NUDO_INFO
NaN    19896
1.0     3664
2.0     1596
4.0     1298
Name: count, dtype: int64

In [42]:
df["NUDO_DESC"] = df["NUDO"].map({
    1: "En intersección o nudo",
    2: "Fuera de intersección o nudo"
}).fillna("Sin información")

In [43]:
df["NUDO_INFO_DESC"] = df["NUDO_INFO_DESC"].fillna("Sin información")

In [44]:
df["NUDO_INFO_DESC"].isna().sum()

np.int64(0)

In [45]:
df["TIPO_ACCIDENTE"].value_counts(dropna=False)

TIPO_ACCIDENTE
2.0     11633
4.0      9145
7.0      6206
3.0      5467
10.0     4646
20.0     3313
9.0      2487
19.0     1706
6.0      1439
1.0      1409
12.0     1042
5.0       945
16.0      896
15.0      466
18.0      373
14.0      239
8.0       188
17.0       70
13.0       51
11.0       34
NaN         7
Name: count, dtype: int64

In [46]:
tipo_accidente_dic = pd.read_excel(
    "../data/raw/dgt/Diccionario_Tabla_Accidentes.xlsx",
    sheet_name="TIPO_ACCIDENTE",
    header=1
)

tipo_accidente_dic

    Valor                                           Etiqueta
0       1  Frontal                                       ...
1       2  Fronto-lateral                                ...
2       3  Lateral                                       ...
3       4  Por alcance                                   ...
4       5  Múltiple o en caravana                        ...
5       6  Colisión contra obstáculo o elemento de la vía...
6       7  Atropello a personas                          ...
7       8  Atropello a animales                          ...
8       9  Vuelco                                        ...
9      10  Caída                                         ...
10     11  Sólo salida de la vía                         ...
11     12  Salida de la vía por la izquierda con colisión...
12     13  Salida de la vía por la izquierda con despeñam...
13     14  Salida de la vía por la izquierda con vuelco  ...
14     15  Salida de la vía por la izquierda, otro tipo  ...
15     16  Salida de la vía por la derecha con colisión  ...
16     17  Salida de la vía por la derecha con despeñamie...
17     18  Salida de la vía por la derecha con vuelco    ...
18     19  Salida de la vía por la derecha otro tipo     ...
19     20  Otro tipo de accidente                        ...

In [47]:
tipo_accidente_dic["Etiqueta"] = tipo_accidente_dic["Etiqueta"].str.strip()

mapa_tipo_accidente = dict(zip(
    tipo_accidente_dic["Valor"],
    tipo_accidente_dic["Etiqueta"]
))

df["TIPO_ACCIDENTE_DESC"] = (
    df["TIPO_ACCIDENTE"]
    .map(mapa_tipo_accidente)
    .fillna("Sin información")
)

In [48]:
df["TIPO_ACCIDENTE_DESC"].value_counts(dropna=False)

TIPO_ACCIDENTE_DESC
Fronto-lateral                                         11633
Por alcance                                             9145
Atropello a personas                                    6206
Lateral                                                 5467
Caída                                                   4646
Otro tipo de accidente                                  3313
Vuelco                                                  2487
Salida de la vía por la derecha otro tipo               1706
Colisión contra obstáculo o elemento de la vía          1439
Frontal                                                 1409
Salida de la vía por la izquierda con colisión          1042
Múltiple o en caravana                                   945
Salida de la vía por la derecha con colisión             896
Salida de la vía por la izquierda, otro tipo             466
Salida de la vía por la derecha con vuelco               373
Salida de la vía por la izquierda con vuelco             239
Atropello a animales                                     188
Salida de la vía por la derecha con despeñamiento         70
Salida de la vía por la izquierda con despeñamiento       51
Sólo salida de la vía                                     34
Sin información                                            7
Name: count, dtype: int64

In [49]:
df["TIPO_VIA"].value_counts(dropna=False)

TIPO_VIA
9     26473
14    13070
6      5228
3      3937
2      1989
5       565
10      166
7       110
8        95
1        68
11       28
13       17
4        12
12        4
Name: count, dtype: int64

In [50]:
tipo_via_dic = pd.read_excel(
    "../data/raw/dgt/Diccionario_Tabla_Accidentes.xlsx",
    sheet_name="TIPO_VIA",
    header=1
)

tipo_via_dic

    Valor                                 Etiqueta
0       1                       Autopista de peaje
1       2                          Autopista libre
2       3                                  Autovía
3       4                     Vía para automóviles
4       5  Carretera Convencional de doble calzada
5       6  Carretera Convencional de calzada única
6       7                          Vía de servicio
7       8                          Ramal de enlace
8       9                                    Calle
9      10                           Camino vecinal
10     11                       Recinto delimitado
11     12                             Vía ciclista
12     13                           Senda ciclable
13     14                                     Otro

In [51]:
mapa_tipo_via = dict(zip(
    tipo_via_dic["Valor"],
    tipo_via_dic["Etiqueta"]
))

df["TIPO_VIA_DESC"] = df["TIPO_VIA"].map(mapa_tipo_via)

In [52]:
resumen_columnas = pd.DataFrame({
    "tipo": df.dtypes,
    "nulos": df.isna().sum(),
    "porcentaje_nulos": (df.isna().mean() * 100).round(2),
    "valores_unicos": df.nunique()
})

resumen_columnas

                      tipo  nulos  porcentaje_nulos  valores_unicos
ID_ACCIDENTE         int64      0               0.0           51762
ANYO                 int64      0               0.0               1
MES                  int64      0               0.0              12
DIA_SEMANA           int64      0               0.0               7
HORA                 int64      0               0.0              24
...                    ...    ...               ...             ...
ZONA_DESC              str      0               0.0               4
NUDO_INFO_DESC         str      0               0.0              14
NUDO_DESC              str      0               0.0               3
TIPO_ACCIDENTE_DESC    str      0               0.0              21
TIPO_VIA_DESC          str      0               0.0              14

[81 rows x 4 columns]

In [53]:
resumen_columnas[resumen_columnas["nulos"] > 0]

                     tipo  nulos  porcentaje_nulos  valores_unicos
KM                float64  38676             74.72            4892
TIPO_ACCIDENTE    float64      7              0.01              20
NUDO              float64      5              0.01               2
NUDO_INFO         float64  19901             38.45              13
CONDICION_NIEBLA  float64  44848             86.64               2
CONDICION_VIENTO  float64  51684             99.85               1

In [54]:
df[[
    "TOTAL_MU24H",
    "TOTAL_HG24H",
    "TOTAL_HL24H",
    "TOTAL_VICTIMAS_24H",
    "TOTAL_VEHICULOS"
]].describe()

,TOTAL_MU24H,TOTAL_HG24H,TOTAL_HL24H,TOTAL_VICTIMAS_24H,TOTAL_VEHICULOS
count,51762.000000,51762.000000,51762.000000,51762.000000,51762.000000
mean,0.008597,0.072698,1.227928,1.309223,1.786252
std,0.102628,0.288609,0.823888,0.811741,0.730048
min,0.000000,0.000000,0.000000,1.000000,0.000000
25%,0.000000,0.000000,1.000000,1.000000,1.000000
50%,0.000000,0.000000,1.000000,1.000000,2.000000
75%,0.000000,0.000000,1.000000,1.000000,2.000000
max,6.000000,9.000000,40.000000,49.000000,32.000000

In [55]:
(df["TOTAL_VEHICULOS"] == 0).sum()

np.int64(7)

In [56]:
df.loc[
    df["TOTAL_VEHICULOS"] == 0,
    ["TIPO_ACCIDENTE_DESC", "TOTAL_VICTIMAS_24H", "ZONA_DESC"]
]

      TIPO_ACCIDENTE_DESC  TOTAL_VICTIMAS_24H ZONA_DESC
18490     Sin información                   2     Calle
31823     Sin información                   1     Calle
32227     Sin información                   1     Calle
45425     Sin información                   2     Calle
47017     Sin información                   1     Calle
47473     Sin información                   1     Calle
51479     Sin información                   1     Calle

In [57]:
df.loc[df["TOTAL_VEHICULOS"] == 0, "TIPO_ACCIDENTE"].isna().sum()

np.int64(7)

In [58]:
df["REGISTRO_INCOMPLETO"] = (
    (df["TOTAL_VEHICULOS"] == 0) &
    (df["TIPO_ACCIDENTE"].isna())
).astype(int)

In [59]:
df["REGISTRO_INCOMPLETO"].value_counts()

REGISTRO_INCOMPLETO
0    51755
1        7
Name: count, dtype: int64

In [60]:
(
    df["TOTAL_VICTIMAS_24H"]
    != df["TOTAL_MU24H"] + df["TOTAL_HG24H"] + df["TOTAL_HL24H"]
).sum()

np.int64(0)

In [61]:
df["DIA_SEMANA"].value_counts().sort_index()

DIA_SEMANA
1    7864
2    7781
3    7766
4    8001
5    8398
6    6491
7    5461
Name: count, dtype: int64

In [62]:
mapa_dias = {
    1: "Lunes",
    2: "Martes",
    3: "Miércoles",
    4: "Jueves",
    5: "Viernes",
    6: "Sábado",
    7: "Domingo"
}

df["DIA_SEMANA_DESC"] = df["DIA_SEMANA"].map(mapa_dias)

In [63]:
df["FIN_SEMANA"] = df["DIA_SEMANA"].isin([6, 7]).astype(int)

In [64]:
df["FIN_SEMANA"].value_counts()

FIN_SEMANA
0    39810
1    11952
Name: count, dtype: int64

In [65]:
def clasificar_franja(hora):
    if 0 <= hora < 6:
        return "Madrugada"
    elif 6 <= hora < 12:
        return "Mañana"
    elif 12 <= hora < 18:
        return "Tarde"
    else:
        return "Noche"

df["FRANJA_HORARIA"] = df["HORA"].apply(clasificar_franja)

In [66]:
df["FRANJA_HORARIA"].value_counts()

FRANJA_HORARIA
Tarde        19917
Noche        14721
Mañana       13805
Madrugada     3319
Name: count, dtype: int64

In [67]:
df["ACCIDENTE_GRAVE"] = (
    (df["TOTAL_MU24H"] > 0) |
    (df["TOTAL_HG24H"] > 0)
).astype(int)

In [68]:
df["ACCIDENTE_GRAVE"].value_counts()

ACCIDENTE_GRAVE
0    47960
1     3802
Name: count, dtype: int64

In [69]:
df["ACCIDENTE_MORTAL"] = (
    df["TOTAL_MU24H"] > 0
).astype(int)

In [70]:
df["ACCIDENTE_MORTAL"].value_counts()

ACCIDENTE_MORTAL
0    51352
1      410
Name: count, dtype: int64

In [71]:
df["TIENE_HERIDOS_GRAVES"] = (
    df["TOTAL_HG24H"] > 0
).astype(int)

In [72]:
df["TIENE_HERIDOS_GRAVES"].value_counts()

TIENE_HERIDOS_GRAVES
0    48309
1     3453
Name: count, dtype: int64

In [73]:
df.shape

(51762, 88)

In [74]:
df.to_csv(
    "../data/processed/accidentes_2024_limpio.csv",
    index=False
)

In [75]:
Path("../data/processed/accidentes_2024_limpio.csv").exists()

True